# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=70)),
                ('population', models.IntegerField(default=0)),
                ('event_image', models.ImageField(null=True, upload_to='pictures/')),
            ],
        ),
    ]
