# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0002_village'),
    ]

    operations = [
        migrations.RenameField(
            model_name='village',
            old_name='event_image',
            new_name='village_image',
        ),
    ]
